apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mongo-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: flask-mongo
  template:
    metadata:
      labels:
        app: flask-mongo
    spec:
      containers:
        - name: flask-app
          image: bitsatwar/calorie-app:latest
          ports:
            - containerPort: 5000 
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/test"
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage  
              mountPath: /data/db 
      volumes:
        - name: mongo-storage
          emptyDir: {}
