version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      DOCKERIZED: '1' 

  mongo:
    image: mongo
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db
      - ./insert_food_data.py:/docker-entrypoint-initdb.d/insert_food_data.py

volumes:
  mongo_data:
