name: Running Code Coverage
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 7.0.2
    - name: Install Python 3.11.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.13
    - name: Install dependencies
      run: |
        pip install pytest-cov pytest
        pip install -r requirements.txt
        pip install openai==0.28.0
        echo requirements installed
    - name: Run the tests
      run: |
        coverage run -m pytest tests/
    - name: Check coverage threshold
      run: |
        COVERAGE=$(coverage report -m | grep 'TOTAL' | awk '{print $4}' | cut -d '%' -f1)
        if [ "$COVERAGE" -lt 60 ]; then
          echo "Coverage is below 60%: $COVERAGE%"
          exit 1
        fi
      shell: bash
