# name: PR Test

# on:
#   pull_request:
#     types: [opened, reopened, synchronize]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     services:
#       mongo:
#         image: mongo
#         ports:
#           - "27017:27017"
#         options: --health-cmd "mongo --eval 'db.stats().ok'" --health-interval 10s --health-timeout 5s --health-retries 3

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Compose
#         run: docker-compose up -d

#       - name: Wait for services to be ready
#         run: |
#           timeout 300s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:5000)" != "200" ]]; do sleep 5; done'

#       - name: Run tests
#         run: |
#           docker-compose exec flask_app coverage run -m pytest tests/

#       - name: Tear down Docker Compose
#         run: docker-compose down
